name: Deploy to AWS API Gateway

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install AWS and SAM CLIs
        run: |
          python -m pip install --upgrade pip
          pip install awscli aws-sam-cli
      - name: Package and deploy SAM application
        run: bash deploy.sh
        env:
          AWS_DEFAULT_REGION: eu-west-1
          LAMBDA_S3_BUCKET_NAME: github-activity-lambda
          GITHUB_OAUTH_CALLBACK_URL: https://app.gitactivity.com/callback_github.html
          GITHUB_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SAM_AND_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SAM_AND_S3_ACCESS_KEY_SECRET }}
