name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install SAM CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
      - run: sam validate
